print("Bienvenido al Sistema de Reparacion Mi Taller Mecanico")
print("-------------------------------------------------------")
print("Seleccione una Opcion:")
print("OPCION 1: Ingresar un Vehiculo")
print("OPCION 2: Generar una Reparacion")
print("OPCION 3: Ingresar un Mecanico")
print("OPCION 4: Ver Vehiculos en lista de Espera")
print("OPCION 5: Ver Mecanicos")
